import React, { useState } from 'react';
import { ProteinStructure, PhysicochemicalProperties } from '../types/protein';
import { calculatePhysicochemicalProperties, digestProtein } from '../utils/bioCalculators';
import { X, Copy, Download, Printer, Check, FileText } from 'lucide-react';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  structure: ProteinStructure;
}

export const ReportModal: React.FC<ReportModalProps> = ({ isOpen, onClose, structure }) => {
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const props = calculatePhysicochemicalProperties(structure.fastaSequence);
  const trypsinFragments = digestProtein(structure.fastaSequence, 'trypsin');

  // Compute Ramachandran summary
  let core = 0, allowed = 0, outlier = 0, totalDihedrals = 0;
  structure.chains.forEach((chain) => {
    chain.residues.forEach((res) => {
      if (typeof res.phi === 'number' && typeof res.psi === 'number') {
        totalDihedrals++;
        if (
          (res.phi >= -110 && res.phi <= -35 && res.psi >= -75 && res.psi <= -15) ||
          (res.phi >= -175 && res.phi <= -65 && res.psi >= 85 && res.psi <= 175)
        ) {
          core++;
        } else if (
          (res.phi >= -180 && res.phi <= -30 && res.psi >= -90 && res.psi <= 180) ||
          (res.phi >= 30 && res.phi <= 90 && res.psi >= 10 && res.psi <= 90)
        ) {
          allowed++;
        } else {
          outlier++;
        }
      }
    });
  });

  const favoredPct = totalDihedrals > 0 ? ((core / totalDihedrals) * 100).toFixed(1) : 'N/A';

  const reportMarkdown = `# ProteinX Structural & Biochemical Analysis Report
**Protein ID:** ${structure.metadata.id || 'N/A'}
**Title:** ${structure.metadata.title || 'N/A'}
**Organism:** ${structure.metadata.organism || 'N/A'}
**Resolution:** ${structure.metadata.resolution ? `${structure.metadata.resolution} Å` : 'N/A'}
**Experimental Method:** ${structure.metadata.method || 'X-ray Crystallography'}
**Deposition Date:** ${structure.metadata.depositionDate || 'N/A'}

---

## 1. Primary Sequence & Physicochemical Properties
- **Residue Count:** ${props.length} amino acids
- **Molecular Weight:** ${props.molecularWeight.toLocaleString()} Da (${(props.molecularWeight / 1000).toFixed(2)} kDa)
- **Theoretical Isoelectric Point (pI):** ${props.isoelectricPoint}
- **Net Charge at pH 7.4:** ${props.netChargeAtPh7 > 0 ? '+' : ''}${props.netChargeAtPh7}
- **Molar Extinction Coefficient (280nm, Cystines formed):** ${props.extinctionCoefficientCystine} M⁻¹ cm⁻¹
- **Molar Extinction Coefficient (280nm, Reduced):** ${props.extinctionCoefficientReduced} M⁻¹ cm⁻¹
- **Absorbance A280 (0.1% = 1 g/L):** ${props.absorbance280}
- **GRAVY (Grand Average of Hydropathicity):** ${props.gravy}
- **Aliphatic Index:** ${props.aliphaticIndex}

## 2. Stereochemical Validation (Ramachandran Plot)
- **Total Validated Dihedral Angles:** ${totalDihedrals}
- **Residues in Core Favored Regions:** ${core} (${favoredPct}%)
- **Residues in Allowed Regions:** ${allowed}
- **Outliers (Steric Clashes):** ${outlier}

## 3. In-Silico Proteomics Digestion (Trypsin)
- **Predicted Peptides:** ${trypsinFragments.length} fragments
${trypsinFragments
  .slice(0, 10)
  .map((f) => `- [${f.start}-${f.end}] Mass: ${f.mass} Da | [M+2H]²⁺: ${f.charge2Mz} | ${f.sequence}`)
  .join('\n')}

---
*Generated by ProteinX Studio on ${new Date().toLocaleDateString()}*
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const data = {
      metadata: structure.metadata,
      properties: props,
      ramachandran: { totalDihedrals, core, allowed, outlier, favoredPercentage: favoredPct },
      trypsinDigestion: trypsinFragments,
      sequence: structure.fastaSequence,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${structure.metadata.id || 'Protein'}_analysis_report.json`;
    link.click();
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-800">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Comprehensive Analysis Report</h3>
              <p className="text-xs text-slate-400">
                {structure.metadata.id || 'Protein'} • Biophysical, structural, and proteolytic summary
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors"
              title="Copy Markdown"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={handleDownloadJSON}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-400 transition-colors"
              title="Download JSON Report"
            >
              <Download className="w-4 h-4" />
            </button>
            <button
              onClick={handlePrint}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors"
              title="Print Report"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors ml-2"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto flex flex-col gap-6 text-xs text-slate-300 leading-relaxed font-sans">
          {/* Metadata Block */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 bg-slate-950/60 p-4 rounded-xl border border-slate-800">
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Protein ID</span>
              <div className="text-cyan-400 font-bold font-mono text-sm mt-0.5">
                {structure.metadata.id || 'Custom'}
              </div>
            </div>
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Classification</span>
              <div className="text-white font-medium text-xs mt-0.5">
                {structure.metadata.classification || 'Soluble Protein'}
              </div>
            </div>
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Organism</span>
              <div className="text-white font-medium text-xs mt-0.5">
                {structure.metadata.organism || 'N/A'}
              </div>
            </div>
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Resolution</span>
              <div className="text-emerald-400 font-bold font-mono text-xs mt-0.5">
                {structure.metadata.resolution ? `${structure.metadata.resolution} Å` : 'N/A'}
              </div>
            </div>
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Method</span>
              <div className="text-white font-medium text-xs mt-0.5">
                {structure.metadata.method || 'X-Ray Diffraction'}
              </div>
            </div>
            <div>
              <span className="text-slate-500 font-mono text-[10px] uppercase">Chains</span>
              <div className="text-purple-400 font-bold font-mono text-xs mt-0.5">
                {structure.chains.length} ({structure.chains.map((c) => c.id).join(', ')})
              </div>
            </div>
          </div>

          {/* Properties Grid */}
          <div>
            <h4 className="font-bold text-white text-sm mb-3">1. Physicochemical Attributes</h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-slate-400 text-[11px]">Molecular Mass</span>
                <div className="text-emerald-400 font-bold font-mono text-base mt-1">
                  {(props.molecularWeight / 1000).toFixed(2)} kDa
                </div>
                <span className="text-[10px] text-slate-500 font-mono">
                  {props.molecularWeight} Da
                </span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-slate-400 text-[11px]">Isoelectric Point (pI)</span>
                <div className="text-purple-400 font-bold font-mono text-base mt-1">
                  {props.isoelectricPoint}
                </div>
                <span className="text-[10px] text-slate-500">Neutral net charge</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-slate-400 text-[11px]">Net Charge (pH 7.4)</span>
                <div className="text-cyan-400 font-bold font-mono text-base mt-1">
                  {props.netChargeAtPh7 > 0 ? '+' : ''}
                  {props.netChargeAtPh7}
                </div>
                <span className="text-[10px] text-slate-500">Physiological state</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-slate-400 text-[11px]">Absorbance (A280)</span>
                <div className="text-pink-400 font-bold font-mono text-base mt-1">
                  {props.absorbance280}
                </div>
                <span className="text-[10px] text-slate-500">0.1% (1 g/L)</span>
              </div>
            </div>
          </div>

          {/* Stereochemical Quality */}
          <div>
            <h4 className="font-bold text-white text-sm mb-2">2. Stereochemical Conformation</h4>
            <p className="text-slate-400 mb-3">
              Calculated backbone dihedral angles (φ and ψ) mapped onto the Ramachandran conformational landscape.
            </p>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-center">
                <span className="text-emerald-400 font-bold font-mono text-lg">{favoredPct}%</span>
                <div className="text-[11px] text-slate-300 mt-1">Core Favored Regions</div>
              </div>
              <div className="p-3 rounded-xl bg-sky-500/10 border border-sky-500/20 text-center">
                <span className="text-sky-400 font-bold font-mono text-lg">{allowed}</span>
                <div className="text-[11px] text-slate-300 mt-1">Allowed Conformations</div>
              </div>
              <div className="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-center">
                <span className="text-red-400 font-bold font-mono text-lg">{outlier}</span>
                <div className="text-[11px] text-slate-300 mt-1">Conformational Outliers</div>
              </div>
            </div>
          </div>

          {/* FASTA Sequence */}
          <div>
            <h4 className="font-bold text-white text-sm mb-2">3. Primary Sequence (FASTA)</h4>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 font-mono text-xs text-slate-300 tracking-wider break-all select-all">
              &gt;{structure.metadata.id || 'ProteinX'}|{structure.totalResidues} residues
              <br />
              {structure.fastaSequence}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
